### ISSUE TITLE
WithMaximumUtilization

### ISSUE THREAD

**Issue by srameh** [junian/Standard.Licensing#1]
Due to lack of documentation, I was wondering what does the .WithMaximumUtilization(1) would do when a license is generated? Does this mean the license allowed 1 installation? If this is the case how is it validated?

**Comment by mrukas** [comment]
As what i have seen in the source, this only sets the .Quantity property of the license (Per-Developer-License). This is just a property and you would have to implement the logic to check if this limit is exceeded on your own. This could be realized if each installation of your software would register itself with a unique identifier on your own licensing service. You could then prevent activation if too many users have already registered this license.
