### ISSUE TITLE
Validate method not found

### ISSUE THREAD

**Issue by alexrainman** [junian/Standard.Licensing#2]
Cannot calculate validationFailures as License doesn't contain Validate method.

**Comment by pricelessrabbit** [comment]
Validate is an extension method. You can find it [here]( https://github.com/junian/Standard.Licensing/blob/master/src/Standard.Licensing/Validation/LicenseValidationExtensions.cs)

**Comment by junian** [comment]
Make sure to put `using Standard.Licensing.Validation;` at the top before calling `Validate`.
