### ISSUE TITLE
.net6+

### ISSUE THREAD

**Issue by mph911** [junian/Standard.Licensing#20]
Is there any plan to port to .net6+?

**Comment by CraigRichards** [comment]
The .NetStandard 2.0 target framework would cover your .Net6 requirement.

**Comment by AntiGuideAkquinet** [comment]
I believe a change of targeted frameworks would be sensible altough not necessary to use the library in .NET 6.

As suggested [here](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#older-targets) a switch to support `netstandard2.0` (and `net461` explicity) would bring us in line with other widespread librarys and allow usage of a few new features.

That means dropping following targets:
- `net45`
- `net40`
- `portable-net45+win8+wpa81+wp8`
- `portable-net403+sl50+win8+wp8`

And keeping/adding:
- `netstandard2.0`
- `net461`

From the linked page:

> .NET Standard 1.x is distributed as a granular set of NuGet packages, which creates a large package dependency graph and results in developers downloading a lot of packages when building. Modern .NET implementations support .NET Standard 2.0. You should only target .NET Standard 1.x if you specifically need to target an older platform.

**Comment by mzayarnyuk** [comment]
yes pls add separated targeting;
no one ask to remove standard2.0 etc because someone use that in old projects;
but add new separated targeting make easy to use who want built with own src; and make better perfomance and iluminate aoutdated standard and other old refs that not needed if use in modern net6-7 or maui etc

**Comment by mzayarnyuk** [comment]
is really critical for you, in other way mans will check and choose some new - more bad maybe - but simple implementation that easy to try and integrate with there apps;
