### ISSUE TITLE
Created a UI for this project

### ISSUE THREAD

**Issue by PatrickRainer** [junian/Standard.Licensing#22]
@junian Hi Junian. Thank your making this repo. I used it for one of my projects and created Lisense Manager out of it. It still needs some work. If you like you could refer to it on your readme.

https://github.com/PatrickRainer/LicenseManager

**Comment by skst** [comment]
Since the `PatrickRainer/LicenseManager` project seems to be unsupported, I created a GUI for `Standard.Licensing` as well. Comments are welcome.

https://github.com/skst/LicenseManager
