### ISSUE TITLE
AssertThat throws error if Attribute or Feature deos not exist

### ISSUE THREAD

**Issue by MikeWilliams-UK** [junian/Standard.Licensing#30]
In a .Net Framework (4.6.2) application.

If you have a licence which has been generated with an attribue of "Random1" and when you validate it you try to get an attribute of "Random2" you get a System.NullReferenceException when using .AssertThat(lic => lic.AdditionalAttributes.Get("Random2")

Same happens if you specify a feature which does not exist in the licence.

I would expect both of these to gracefully fail validation with a message similar to "Attribute 'Random2' not present in the licence."

**Comment by SamKr** [comment]
If anyone comes across this, the correct way to implement this can be found in @junian's [tests projects](https://github.com/junian/Standard.Licensing/blob/master/src/Standard.Licensing.Tests/LicenseValidationTests.cs) for Standard.Licensing.

Example:

```csharp
var validationFailures = license.Validate()
    .ExpirationDate(systemDateTime: DateTime.Now)
    .When(lic => lic.Type == LicenseType.Trial)
    .And()
    .Signature(EncryptedPublicKey)
    .And()
    .AssertThat(lic => lic.ProductFeatures.Contains("Sales Module"), new GeneralValidationFailure { Message = "Sales Module not licensed!" })
    .AssertValidLicense();
```

You can change `Sales Module` into anything you want, and it'll trigger the corresponding failure if it's not present in the license.

**Comment by junian** [comment]
Thanks for pointing that @SamKr
