### ISSUE TITLE
Update BouncyCastle to latest version

### ISSUE THREAD

**Issue by ahmadreza-hadidi** [junian/Standard.Licensing#35]
Hi, @junian  Thank you for your good work
Please update BouncyCastle to latest version because of vulnerability in older versions

**Comment by junian** [comment]
Hi @ahmadreza-hadidi, Can you give reference which vulnerability?

**Comment by kfrancis** [comment]
https://github.com/advisories/GHSA-8xfc-gm6g-vgpv
https://github.com/advisories/GHSA-v435-xc8x-wvr9
https://github.com/advisories/GHSA-8xfc-gm6g-vgpv

![image](https://github.com/junian/Standard.Licensing/assets/67574/9a607ab9-65c4-4be6-875e-b9fae5d32004)

You're also using a forked version, it looks like. Can you please use the standard version? https://www.nuget.org/packages/BouncyCastle.Cryptography

They updated it to remove the need to use the portable version when they depreciated the BouncyCastle.Crypto version.

**Comment by kfrancis** [comment]
https://www.nuget.org/packages/BouncyCastle

**Comment by kfrancis** [comment]
I do understand that you're using 1.9.0, but there's an official package so you don't need to reference the external repo.

**Comment by kfrancis** [comment]
This is the other reason why it's important. Can't use packages with vulnerabilities, and can't use the standard library because yours brings in a transitive reference:

![image](https://github.com/junian/Standard.Licensing/assets/67574/69dd2ac4-3a10-4962-bff3-d50a635b480a)

I've put a pull request together to fix all that up.

**Comment by kfrancis** [comment]
@junian Have you had a chance to check the pull request?

**Comment by junian** [comment]
Thank you. I'll review it soon.

**Comment by kfrancis** [comment]
Appreciate it. It's somewhat urgent.

**Comment by junian** [comment]
Thank you @kfrancis for the contribution, it's being validated on NuGet right now, should be available soon.

**Comment by kfrancis** [comment]
The release works great, thank you. Also, I can confirm that the change in BouncyCastle doesn't require a change in existing licenses - they work as is.
