### ISSUE TITLE
How to generate .lic for a product wich works in a specific machine

### ISSUE THREAD

**Issue by SonaBIMDev** [junian/Standard.Licensing#8]
Hi
First of all, thx for your Code :-)
I'd like to generate a lic file with a keyProduct wichh work only one and unique machine. I mean, if the program user move the file to another computer, it won't be work. Is it possible?

**Comment by lastlink** [comment]
@pierrenavarra I've been encrypting and decrypting my licenses, but the most secure way is to use info from the license and validate with a server and possibly store the response in a cache (I'm in the process of building my own). You can generate your own unique id and store it in the license and validate on this, but users can change it unless your license is encrypted or the unique ids are pulled from a server.
