### ISSUE TITLE
How to use in license server that package?

### ISSUE THREAD

**Issue by mesutdede** [junian/Standard.Licensing#9]
Hi!
I have a windows service that I want to license on the remote server. For example, I will give my client license key for 2 servers. Cannot install on 3rd server. Can I perform this editing with this package? Why?

**Comment by lastlink** [comment]
see my comment in https://github.com/junian/Standard.Licensing/issues/8#issuecomment-527931051

**Comment by mesutdede** [comment]
Hi @lastlink ,
Can you share sample code

**Comment by lastlink** [comment]
You'd have to as part of your license verification check against a device id. standard licensing just validates that the license works and pulls out attributes. To lock to a machine you'll have to write your own logic to compare against a device id.

**Comment by mesutdede** [comment]
Ok. Thank you so much.
